//! Loopback HTTP server hosting the web UI and the command/event bridge.
//!
//! Replaces wry's IPC + custom-protocol transport with plain HTTP so
//! command failures surface as real responses (400s) instead of silently
//! dropped messages, and so the same UI can be opened in a normal browser
//! during development.
//!
//! Hand-rolled on `std::net` (rather than a general-purpose HTTP crate)
//! because the SSE endpoint must stream and flush incrementally — buffered
//! writers that only flush at end-of-response deadlock it.
//!
//! Security posture (privacy-first, offline app):
//!   * bound to `127.0.0.1` on a randomly chosen port
//!   * every request must carry a per-launch random token (query param, the
//!     cookie set on the first HTML response, or a same-origin
//!     `Sec-Fetch-Site` request that browsers do not let pages forge)
//!   * no routes beyond static UI assets, `POST /cmd`, and `GET /events`

use std::collections::VecDeque;
use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::mpsc::Sender;
use std::sync::{Arc, Condvar, Mutex};
use std::thread::JoinHandle;
use std::time::Duration;

use crate::web_bridge::EventBus;
use crate::web_shell::UiCommand;

/// The embedded UI bundle, built by `apps/wisp-desktop/ui` (`npm run build`).
/// A fresh checkout without a UI build falls back to a placeholder page.
static UI_ASSETS: include_dir::Dir<'_> = include_dir::include_dir!("$CARGO_MANIFEST_DIR/ui/dist");

const FALLBACK_PAGE: &str = r#"<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Wisp</title></head>
<body style="font-family: system-ui; background:#0b0e13; color:#e8eaed; display:flex; height:100vh; align-items:center; justify-content:center;">
  <div style="text-align:center;">
    <h1>Wisp</h1>
    <p>The web UI bundle is missing. Build it with:</p>
    <pre><code>cd apps/wisp-desktop/ui &amp;&amp; npm install &amp;&amp; npm run build</code></pre>
    <p>then restart the app.</p>
  </div>
</body></html>
"#;

/// Max accepted request head / `POST /cmd` body size.
const LIMIT: usize = 64 * 1024;

fn mime_for(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js" | "mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json" | "map") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        _ => "application/octet-stream",
    }
}

/// Serve the embedded UI bundle; SPA-style fallback for route-like paths.
fn serve_ui(path: &str) -> (&'static [u8], &'static str) {
    let normalized = if path.is_empty() { "index.html" } else { path };
    if let Some(file) = UI_ASSETS.get_file(normalized) {
        return (file.contents(), mime_for(normalized));
    }
    // Route-like paths get the app shell; anything that looks like a
    // missing asset 404s so build errors surface clearly.
    if !normalized.contains('.') {
        return match UI_ASSETS.get_file("index.html") {
            Some(file) => (file.contents(), mime_for("index.html")),
            None => (FALLBACK_PAGE.as_bytes(), "text/html; charset=utf-8"),
        };
    }
    (b"not found\n", "text/plain; charset=utf-8")
}

fn query_params(query: &str) -> Vec<(String, String)> {
    query
        .split('&')
        .filter_map(|pair| pair.split_once('='))
        .map(|(k, v)| (k.to_owned(), v.to_owned()))
        .collect()
}

fn header_value<'a>(
    headers: &'a [(String, String)],
    name: &str,
) -> Option<&'a str> {
    headers
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case(name))
        .map(|(_, v)| v.as_str())
}

/// Token check accepting any of: `?token=` query, the session cookie set on
/// the first HTML response, or a same-origin sub-resource request (the
/// `Sec-Fetch-Site` header is set by the browser and cannot be forged by
/// page scripts). Sub-resources cannot carry the query token: asset URLs are
/// generated by the bundler without it.
fn token_ok(
    headers: &[(String, String)],
    query: &str,
    token: &str,
) -> bool {
    if query_params(query)
        .iter()
        .any(|(k, v)| k == "token" && v == token)
    {
        return true;
    }
    if let Some(cookies) = header_value(headers, "Cookie")
        && cookies.contains(&format!("__wisp_token={token}"))
    {
        return true;
    }
    header_value(headers, "Sec-Fetch-Site").is_some_and(|site| site == "same-origin")
}

/// Shared byte queue feeding an SSE response body.
struct SsePipe {
    state: Mutex<SseState>,
    available: Condvar,
}

struct SseState {
    queue: VecDeque<u8>,
    closed: bool,
}

impl SsePipe {
    fn new() -> Self {
        Self {
            state: Mutex::new(SseState {
                queue: VecDeque::new(),
                closed: false,
            }),
            available: Condvar::new(),
        }
    }

    fn push(
        &self,
        payload: &str,
    ) {
        let Ok(mut state) = self.state.lock() else {
            return;
        };
        state.queue.extend(payload.as_bytes().iter().copied());
        self.available.notify_all();
    }

    fn close(&self) {
        let Ok(mut state) = self.state.lock() else {
            return;
        };
        state.closed = true;
        self.available.notify_all();
    }

    /// Copy up to `buf.len()` bytes out, blocking while the queue is empty.
    /// Returns 0 once the bus disconnected the stream.
    fn take(
        &self,
        buf: &mut [u8],
    ) -> usize {
        let Ok(mut state) = self.state.lock() else {
            return 0;
        };
        loop {
            if !state.queue.is_empty() {
                let len = buf.len().min(state.queue.len());
                for byte in buf.iter_mut().take(len) {
                    if let Some(popped) = state.queue.pop_front() {
                        *byte = popped;
                    }
                }
                return len;
            }
            if state.closed {
                return 0;
            }
            let Ok(next) = self
                .available
                .wait_timeout(state, Duration::from_secs(30))
                .map(|(guard, _)| guard)
            else {
                return 0;
            };
            state = next;
        }
    }
}

struct ParsedRequest {
    method: String,
    path: String,
    query: String,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
}

/// Read one request head (and body, when a capped Content-Length is given).
/// All responses use `Connection: close`, so a single request per
/// connection is all we need to parse.
fn read_request(stream: &mut TcpStream) -> std::io::Result<ParsedRequest> {
    let mut buf = Vec::with_capacity(1024);
    let mut chunk = [0u8; 1024];
    let head_end = loop {
        if let Some(position) = buf.windows(4).position(|window| window == b"\r\n\r\n") {
            break position + 4;
        }
        let read = stream.read(&mut chunk)?;
        if read == 0 {
            return Err(std::io::Error::other("connection closed mid-request"));
        }
        buf.extend_from_slice(&chunk[..read]);
        if buf.len() > LIMIT {
            return Err(std::io::Error::other("request head too large"));
        }
    };

    // Anything after the head is already (part of) the body: a single TCP
    // segment often carries head + body together, and the bytes must not be
    // read from the socket again.
    let text = String::from_utf8_lossy(&buf[..head_end]);
    let mut lines = text.split("\r\n");
    let request_line = lines.next().unwrap_or_default();
    let mut parts = request_line.split(' ');
    let method = parts.next().unwrap_or_default().to_owned();
    let target = parts.next().unwrap_or_default().to_owned();
    let (path, query) = target.split_once('?').unwrap_or((target.as_str(), ""));

    let mut headers = Vec::new();
    for line in lines {
        if line.is_empty() {
            continue;
        }
        if let Some((name, value)) = line.split_once(':') {
            headers.push((name.trim().to_owned(), value.trim().to_owned()));
        }
    }

    let content_length = header_value(&headers, "Content-Length")
        .and_then(|value| value.parse::<usize>().ok())
        .unwrap_or(0);
    if content_length > LIMIT {
        return Err(std::io::Error::other("request body too large"));
    }
    let mut body = buf[head_end..].to_vec();
    if body.len() > content_length {
        body.truncate(content_length);
    } else if body.len() < content_length {
        let mut rest = vec![0u8; content_length - body.len()];
        stream.read_exact(&mut rest)?;
        body.extend_from_slice(&rest);
    }

    Ok(ParsedRequest {
        method,
        path: path.to_owned(),
        query: query.to_owned(),
        headers,
        body,
    })
}

fn write_response(
    stream: &mut TcpStream,
    status: &str,
    extra_headers: &[(&'static str, String)],
    body: &[u8],
) -> std::io::Result<()> {
    let mut head = format!(
        "HTTP/1.1 {status}\r\nContent-Length: {}\r\nConnection: close\r\n",
        body.len()
    );
    for (name, value) in extra_headers {
        head.push_str(name);
        head.push_str(": ");
        head.push_str(value);
        head.push_str("\r\n");
    }
    head.push_str("\r\n");
    stream.write_all(head.as_bytes())?;
    stream.write_all(body)?;
    stream.flush()
}

/// Stream SSE events to one client; blocks until the client disconnects or
/// the event bus shuts down.
fn serve_events(
    stream: &mut TcpStream,
    bus: &EventBus,
) -> std::io::Result<()> {
    let receiver = bus.subscribe();
    let head = "HTTP/1.1 200 OK\r\n\
        Content-Type: text/event-stream\r\n\
        Cache-Control: no-cache\r\n\
        Access-Control-Allow-Origin: *\r\n\
        Connection: keep-alive\r\n\r\n";
    stream.write_all(head.as_bytes())?;
    stream.flush()?;

    let pipe = Arc::new(SsePipe::new());
    let pump_pipe = pipe.clone();
    std::thread::spawn(move || {
        for payload in receiver {
            pump_pipe.push(&format!("data: {payload}\n\n"));
        }
        pump_pipe.close();
    });

    let mut buf = [0u8; 4096];
    loop {
        let len = pipe.take(&mut buf);
        if len == 0 {
            return Ok(());
        }
        stream.write_all(&buf[..len])?;
        stream.flush()?;
    }
}

fn handle_connection(
    mut stream: TcpStream,
    token: &str,
    cmd_tx: &Sender<UiCommand>,
    bus: &EventBus,
    dev_cors: bool,
) {
    let _ = stream.set_nodelay(true);
    let _ = stream.set_read_timeout(Some(Duration::from_secs(30)));

    let Ok(request) = read_request(&mut stream) else {
        return;
    };
    let cors: Vec<(&'static str, String)> = if dev_cors {
        vec![("Access-Control-Allow-Origin", "*".to_owned())]
    } else {
        Vec::new()
    };

    if !token_ok(&request.headers, &request.query, token) {
        let _ = write_response(&mut stream, "403 Forbidden", &cors, b"forbidden\n");
        return;
    }

    match (request.method.as_str(), request.path.as_str()) {
        ("GET", "/events") => {
            let _ = serve_events(&mut stream, bus);
        },
        ("POST", "/cmd") => {
            // Surface contract bugs loudly instead of dropping them.
            match serde_json::from_slice::<UiCommand>(&request.body) {
                Ok(command) => {
                    let _ = cmd_tx.send(command);
                    let _ = write_response(&mut stream, "204 No Content", &cors, b"");
                },
                Err(error) => {
                    eprintln!("wisp-webview: rejected command {:?}: {error}", request.body);
                    let message = format!("invalid command: {error}\n");
                    let _ =
                        write_response(&mut stream, "400 Bad Request", &cors, message.as_bytes());
                },
            }
        },
        ("OPTIONS", "/cmd" | "/events") => {
            let headers = vec![
                ("Access-Control-Allow-Origin", "*".to_owned()),
                (
                    "Access-Control-Allow-Methods",
                    "POST, GET, OPTIONS".to_owned(),
                ),
                ("Access-Control-Allow-Headers", "Content-Type".to_owned()),
            ];
            let _ = write_response(&mut stream, "204 No Content", &headers, b"");
        },
        ("GET", _) => {
            let (bytes, mime) = serve_ui(request.path.trim_start_matches('/'));
            let mut headers: Vec<(&'static str, String)> = vec![
                ("Content-Type", mime.to_owned()),
                (
                    "Set-Cookie",
                    format!("__wisp_token={token}; Path=/; SameSite=Strict"),
                ),
            ];
            headers.extend(cors);
            let _ = write_response(&mut stream, "200 OK", &headers, bytes);
        },
        _ => {
            let _ = write_response(
                &mut stream,
                "405 Method Not Allowed",
                &[],
                b"method not allowed\n",
            );
        },
    }
}

/// A running loopback server.
pub struct WebServer {
    /// Root URL including the token, e.g. `http://127.0.0.1:52134/?token=…`.
    pub url: String,
    _join: Option<JoinHandle<()>>,
}

/// Bind `127.0.0.1` on a random port and serve until the process exits.
pub fn spawn(
    cmd_tx: Sender<UiCommand>,
    bus: EventBus,
    dev_cors: bool,
) -> std::io::Result<WebServer> {
    let listener = TcpListener::bind(("127.0.0.1", 0))?;
    let addr = listener.local_addr()?;
    let token = uuid::Uuid::new_v4().simple().to_string();
    let url = format!("http://{addr}/?token={token}");

    let join = std::thread::Builder::new()
        .name("wisp-web-server".into())
        .spawn(move || {
            for stream in listener.incoming() {
                let Ok(stream) = stream else {
                    continue;
                };
                let cmd_tx = cmd_tx.clone();
                let bus = bus.clone();
                let token = token.clone();
                let spawned = std::thread::Builder::new()
                    .name("wisp-web-request".into())
                    .spawn(move || handle_connection(stream, &token, &cmd_tx, &bus, dev_cors));
                if spawned.is_err() {
                    break;
                }
            }
        })?;

    Ok(WebServer {
        url,
        _join: Some(join),
    })
}
