name: setup nix
description: Install Nix and restore the shared Nix store cache
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/determinate-nix-action@v3
    - uses: DeterminateSystems/flakehub-cache-action@main
