name: formal
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-formal
  cancel-in-progress: true
permissions:
  contents: read
  actions: write
  id-token: write
jobs:
  verify:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix
      - run: nix build .#checks.x86_64-linux.formal --print-build-logs
