name: nix
on:
  pull_request:
    paths:
      - "flake.lock"
      - "flake.nix"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nix
  cancel-in-progress: true
permissions:
  contents: read
  actions: write
  id-token: write
jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix
      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      - run: nix develop .#ci --quiet --command nixfmt --check flake.nix
