name: nix
on:
  pull_request:
    paths:
      - "flake.lock"
      - "flake.nix"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nix
  cancel-in-progress: true
permissions:
  contents: read
  actions: write
  id-token: write
jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup-nix
      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      - run: nix develop .#ci --quiet --command nixfmt --check flake.nix
