name: nix
on:
  pull_request:
    paths:
      - "flake.lock"
      - "flake.nix"
      - "apps/wisp-desktop/**"
      - ".github/workflows/nix.yaml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nix
  cancel-in-progress: true
permissions:
  contents: read
  actions: write
  id-token: write
jobs:
  check:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-nix
      - uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13
      - run: nix develop .#default --quiet --command nixfmt --check flake.nix apps/wisp-desktop/package.nix
      - run: nix flake check --print-build-logs
